app/routes/auth.py
from flask import Flask, Blueprint, render_template, redirect, url_for, flash, get_flashed_messages, request, abort
from flask_login import login_required, login_user, logout_user, current_user
from app.models import Admin
from app.forms import RegisterForm, LoginForm

auth_bp = Blueprint("auth", __name__)

# @auth_bp.route('/auth/register', methods=['GET'])
# def register():
#     if Admin().check_for_admin():
#         return abort(404)
#     return render_template('/auth/register.html', form=RegisterForm(), message=get_flashed_messages())

# @auth_bp.route('/auth/add/admin', methods=['POST'])
# def add_admin():
#     form = RegisterForm()
#     if not form.validate_on_submit():
#         flash(list(form.errors.values())[0])
#         return redirect(url_for('auth.register'))
    
#     new_admin = Admin(username=request.form.get('username'), password=request.form.get('password')).create_user()
#     if not new_admin:
#         flash('Something went wrong. Please try again.')
#         return redirect(url_for('auth.register'))

#     login_user(new_admin)
#     return redirect(url_for('admin.dashboard'))

# Above is commented out to prevent a new user registering once the first admin is registered.

@auth_bp.route('/auth/login', methods=['GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin.dashboard'))
    return render_template('/auth/login.html', form=LoginForm(), message=get_flashed_messages())

@auth_bp.route('/auth/login/attempt', methods=['POST'])
def login_attempt():
    usr = Admin().login_attempt(request.form.get('username'), request.form.get('password'))
    if not usr:
        flash('Incorrect Login Details.')
        return redirect(url_for('auth.login'))
    
    login_user(usr)
    return redirect(url_for('admin.dashboard'))

@auth_bp.route('/auth/logout', methods=['GET'])
def logout():
    if not current_user.is_authenticated:
        return abort(404)
    logout_user()
    return redirect(url_for('auth.login'))

app/routes/main.py
from flask import Flask, Blueprint, render_template, redirect, url_for, abort
from app.models import Category, Post

main_bp = Blueprint("main", __name__)

@main_bp.route('/', methods=['GET'])
def index():
    return render_template('/main/index.html', categories=Category().fetch_categories(), posts=Post().all_posts(), new=Post().last_submission())

@main_bp.route('/<string:title>', methods=['GET'])
def view_post(title):
    query = Post().custom_query('title', title)
    
    if not query:
        return abort(404)
    return render_template('/main/post.html', post=query, categories=Category().fetch_categories(), new=Post().last_submission())

@main_bp.route('/category/<string:category>', methods=['GET'])
def category_page(category):
    query = Post().posts_by_category(category)
    if not query:
        return redirect(url_for('main.index'))
    return render_template('/main/index.html', posts=query, categories=Category().fetch_categories(), new=Post().last_submission())

app/templates/includes/admin-navigation.html
{% if current_user.is_authenticated %}
    <div class="logged-in-nav">
        <div class="nav-branding">
            <h1>👋<span id="welcome-heading">Hello, Neil.</span></h1>
        </div>
        <div class="logged-in-links">
            <ul>
                <li>
                    <a href="{{url_for('admin.dashboard')}}">
                        <i class="fas fa-home"></i>
                        Dashboard
                    </a>
                </li>
                <li>
                    <a href="{{url_for('auth.logout')}}">
                        <i class="fas fa-sign-out-alt"></i>
                        logout
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="mobile-nav">
        <i onclick="openNav()" class="fas fa-bars"></i>
        <i onclick="closeNav()" class="fas fa-times"></i>
    </div>
    <div class="mobile-links">
        <ul>
            <li>
                <a href="{{url_for('admin.dashboard')}}">
                    <i class="fas fa-home"></i>
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{{url_for('auth.logout')}}">
                    <i class="fas fa-sign-out-alt"></i>
                    logout
                </a>
            </li>
        </ul>
    </div>
{% endif %}
<nav>
    <div class="nav-branding">
        <a href="{{url_for('main.index')}}">
            <h1>neilWrites</h1>
        </a>
    </div>
    <div class="nav-links">
        <ul>
            <li>
                <a href="{{url_for('admin.categories')}}">
                    Categories
                </a>
            </li>
            <li>
                <a href="{{url_for('admin.posts')}}">
                    Posts
                </a>
            </li>
        </ul>
    </div>
</nav>

app/templates/includes/front-navigation.html
{% if current_user.is_authenticated %}
    <div class="logged-in-nav">
        <div class="nav-branding">
            <h1>👋<span id="welcome-heading">Hello, Neil.</span></h1>
        </div>
        <div class="logged-in-links">
            <ul>
                <li>
                    <a href="{{url_for('admin.dashboard')}}">
                        <i class="fas fa-home"></i>
                        Dashboard
                    </a>
                </li>
                <li>
                    <a href="{{url_for('auth.logout')}}">
                        <i class="fas fa-sign-out-alt"></i>
                        logout
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="mobile-nav">
        <i onclick="openNav()" class="fas fa-bars"></i>
        <i onclick="closeNav()" class="fas fa-times"></i>
    </div>
    <div class="mobile-links">
        <ul>
            <li>
                <a href="{{url_for('admin.dashboard')}}">
                    <i class="fas fa-home"></i>
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{{url_for('auth.logout')}}">
                    <i class="fas fa-sign-out-alt"></i>
                    logout
                </a>
            </li>
        </ul>
    </div>
{% endif %}

<nav id="front-nav">
    <div class="nav-branding main">
        <a href="{{url_for('main.index')}}">
            <h1>neilWrites</h1>
        </a>
    </div>
    <div class="nav-links">
        <ul>
            <li>
                <a href="https://neilmcnaught.dev" target="_blank">
                    <i class="far fa-window-maximize"></i>
                </a>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/neil-mcnaught-33b5b4202/" target="_blank">
                    <i class="fab fa-linkedin"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

app/templates/includes/left-sidebar.html
<div class="home-top-icons">
    <div class="home-icon-container">
        <a href="{{url_for('main.index')}}">
            <i class="fas fa-bolt"></i>Home
        </a>
    </div>
    <div class="home-icon-container">
        <a href="https://github.com/MrNaughtZero" target="_blank">
            <i class="fab fa-github"></i>Github
        </a>
    </div>
</div>
<h2 div class="left-block-header"><i class="fas fa-certificate"></i>CATEGORIES</h2>
<div class="left-block-categories">
    {% for item in categories %}
        <a href="{{url_for('main.category_page', category=item.cat)}}">
            <button type="button" class="category-btn">{{item.cat}}</button>
        </a>
    {% endfor %}
</div>
<h2 div class="left-block-header"><i class="fas fa-at"></i>SUBSCRIBE</h2>
<div class="left-block-subscribe">
    <button id="email-sub-btn" onclick="showNewsletterForm()" type="button" class="category-btn">Email</button>
    <button type="button" class="category-btn">Notifications</button>
</div>

 <!-- Mail Chimp Form -->

 <form class="mail-chimp-form" action="https://gmail.us7.list-manage.com/subscribe/post" method="POST">
    <input type="hidden" name="u" value="9d9fe1a38b841d2c3049e03b0">
    <input type="hidden" name="id" value="d23d280744">

    <p class="newsletter-text">Sign up to receive emails when a new post is made. I promise not to spam.</p>
    <!-- people should not fill these in and expect good things -->
    <div id="mergeTable" class="mergeTable">
       <div class="mergeRow dojoDndItem mergeRow-email" id="mergeRow-0">
          <div class="field-group">
             <input type="email" autocapitalize="off" autocorrect="off" name="MERGE0" id="MERGE0" size="25" value="" required placeholder="Email Address">
          </div>
       </div>
    </div>
    <div class="submit_container clear">
       <input type="submit" class="formEmailButton" name="submit" value="Subscribe" class="btn-blue">
    </div>
    <input type="hidden" name="ht" value="620358886350cf5995aecc89baaf5a9a060d971e:MTYxMTA3MDk3Mi41NDc4">
    <input type="hidden" name="mc_signupsource" value="hosted">
 </form>

<!-- Mail Chimp Form End -->
<h2 div class="left-block-header must-read-header"><i class="fab fa-readme"></i>MUST READ</h2>
<a href="{{url_for('main.view_post', title=new.title)}}">
    <div class="must-read-block">
        <h2><b>NEW</b> IN<br>{{new.category}}</h2>
        <p class="must-read-text">{{new.title|replace("-", " ")}}</p>
    </div>
</a>
<p class="copyright">© Neil McNaught</p>

app/templates/includes/scripts.html
<script src="{{url_for('static', filename='scripts/main.js')}}"></script>

app/templates/includes/styles.html
<link href="{{url_for('static', filename='styles/main.css')}}" type="text/css" rel="stylesheet">